// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCroMUsTKbAMJhqh5Ba0kTmkQN1cu1XVaw',
    appId: '1:373166386355:android:9e5e6198e8b131ca45d4c6',
    messagingSenderId: '373166386355',
    projectId: 'card-reader-app-b45fa',
    storageBucket: 'card-reader-app-b45fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABu-6KUCjI4UZd0vM1Ns3Bl0UNMsWsVGU',
    appId: '1:373166386355:ios:bef91130a498647f45d4c6',
    messagingSenderId: '373166386355',
    projectId: 'card-reader-app-b45fa',
    storageBucket: 'card-reader-app-b45fa.firebasestorage.app',
    androidClientId: '373166386355-jvthq6lriupba5gn0c2mcf0i47l50bv1.apps.googleusercontent.com',
    iosClientId: '373166386355-uva08dfmb23er6efc09aceih894chk36.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardReaderApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtdOKU0nDKVdsMCgRuQQZVgaHK8WFYMxs',
    appId: '1:373166386355:web:fb9caa9e48c0c35e45d4c6',
    messagingSenderId: '373166386355',
    projectId: 'card-reader-app-b45fa',
    authDomain: 'card-reader-app-b45fa.firebaseapp.com',
    storageBucket: 'card-reader-app-b45fa.firebasestorage.app',
  );

}