name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
    paths: ["reader_back_end/**"]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push to Dockerhub
      run: |
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/reader_back_end"

        docker build ./reader_back_end --file ./reader_back_end/Dockerfile --tag $IMAGE_NAME:latest
        
        docker push $IMAGE_NAME:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Copy files via SSH to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "reader_back_end/docker-compose-prod.yml"
          target: "/home/ubuntu/"
          strip_components: 1 # removes the reader_back_end prefix


      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          script: |
            echo "${{ secrets.DOCKERHUB_READ_ONLY_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            docker pull "${{ secrets.DOCKERHUB_USERNAME }}/reader_back_end:latest"

            # -d -> detached mode which mean we could do any command in the terminal after this
            docker compose --env-file /home/ubuntu/.env -f /home/ubuntu/docker-compose-prod.yml up -d