name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: ["reader_back_end/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["reader_back_end/**"]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./reader_back_end --file reader_back_end/Dockerfile --tag my-image-name:$(date +%s)
