name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: ["reader_back_end/**"]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push to Dockerhub
      run: |
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/reader_back_end"

        docker build ./reader_back_end --file ./reader_back_end/Dockerfile --tag $IMAGE_NAME:latest
        
        docker push $IMAGE_NAME:latest